// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/towns": {
    params: {};
  };
  "/towns/top-cities": {
    params: {};
  };
  "/towns/shan-highlands": {
    params: {};
  };
  "/towns/southeast": {
    params: {};
  };
  "/towns/:id": {
    params: {
      "id": string;
    };
  };
  "/beaches": {
    params: {};
  };
  "/beaches/:id": {
    params: {
      "id": string;
    };
  };
  "/foods": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/towns" | "/towns/top-cities" | "/towns/shan-highlands" | "/towns/southeast" | "/towns/:id" | "/beaches" | "/beaches/:id" | "/foods" | "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/towns._index.tsx": {
    id: "routes/towns._index";
    page: "/towns";
  };
  "routes/towns.top-cities.tsx": {
    id: "routes/towns.top-cities";
    page: "/towns/top-cities";
  };
  "routes/towns.shan-highlands.tsx": {
    id: "routes/towns.shan-highlands";
    page: "/towns/shan-highlands";
  };
  "routes/towns.southeast.tsx": {
    id: "routes/towns.southeast";
    page: "/towns/southeast";
  };
  "routes/towns.$id.tsx": {
    id: "routes/towns.$id";
    page: "/towns/:id";
  };
  "routes/beaches._index.tsx": {
    id: "routes/beaches._index";
    page: "/beaches";
  };
  "routes/beaches.$id.tsx": {
    id: "routes/beaches.$id";
    page: "/beaches/:id";
  };
  "routes/foods.tsx": {
    id: "routes/foods";
    page: "/foods";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};